[package]
name = "audio-processor"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
rustfft = "6.4.0"
image = { version = "0.25", default-features = false, features = ["png"] }

[dev-dependencies]
tempfile = "3.15"
